name: Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20.9
        uses: actions/setup-node@v3
        with:
          node-version: 20.9

      - name: Install dependencies and packages
        run: npm install

      - name: Run the test script
        run: npm run test:ci